name: Update Instagram Feed
on:
  workflow_dispatch:
  schedule:
    - cron: '12 0 * * *'

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Use Node.js current
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies & run notion
        run: |
          npm ci
          npm run instagram

      - name: Commit & push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add images/instagram
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Instagram feed" && git push)